# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jan/CLionProjects/ProjektSO_Jan_Bzinkowski

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jan/CLionProjects/ProjektSO_Jan_Bzinkowski

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jan/CLionProjects/ProjektSO_Jan_Bzinkowski/CMakeFiles /home/jan/CLionProjects/ProjektSO_Jan_Bzinkowski//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jan/CLionProjects/ProjektSO_Jan_Bzinkowski/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named klient

# Build rule for target.
klient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 klient
.PHONY : klient

# fast build rule for target.
klient/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/klient.dir/build.make CMakeFiles/klient.dir/build
.PHONY : klient/fast

#=============================================================================
# Target rules for targets named generator_klientow

# Build rule for target.
generator_klientow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generator_klientow
.PHONY : generator_klientow

# fast build rule for target.
generator_klientow/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator_klientow.dir/build.make CMakeFiles/generator_klientow.dir/build
.PHONY : generator_klientow/fast

#=============================================================================
# Target rules for targets named pracownik

# Build rule for target.
pracownik: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pracownik
.PHONY : pracownik

# fast build rule for target.
pracownik/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pracownik.dir/build.make CMakeFiles/pracownik.dir/build
.PHONY : pracownik/fast

#=============================================================================
# Target rules for targets named kierownik

# Build rule for target.
kierownik: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kierownik
.PHONY : kierownik

# fast build rule for target.
kierownik/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kierownik.dir/build.make CMakeFiles/kierownik.dir/build
.PHONY : kierownik/fast

#=============================================================================
# Target rules for targets named SO

# Build rule for target.
SO: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SO
.PHONY : SO

# fast build rule for target.
SO/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SO.dir/build.make CMakeFiles/SO.dir/build
.PHONY : SO/fast

#=============================================================================
# Target rules for targets named logger

# Build rule for target.
logger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logger
.PHONY : logger

# fast build rule for target.
logger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/build
.PHONY : logger/fast

#=============================================================================
# Target rules for targets named kasjer

# Build rule for target.
kasjer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kasjer
.PHONY : kasjer

# fast build rule for target.
kasjer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/build
.PHONY : kasjer/fast

src/Logger.o: src/Logger.cpp.o
.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i
.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s
.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/Tables.o: src/Tables.cpp.o
.PHONY : src/Tables.o

# target to build an object file
src/Tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/klient.dir/build.make CMakeFiles/klient.dir/src/Tables.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator_klientow.dir/build.make CMakeFiles/generator_klientow.dir/src/Tables.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pracownik.dir/build.make CMakeFiles/pracownik.dir/src/Tables.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kierownik.dir/build.make CMakeFiles/kierownik.dir/src/Tables.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SO.dir/build.make CMakeFiles/SO.dir/src/Tables.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/src/Tables.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/src/Tables.cpp.o
.PHONY : src/Tables.cpp.o

src/Tables.i: src/Tables.cpp.i
.PHONY : src/Tables.i

# target to preprocess a source file
src/Tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/klient.dir/build.make CMakeFiles/klient.dir/src/Tables.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator_klientow.dir/build.make CMakeFiles/generator_klientow.dir/src/Tables.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pracownik.dir/build.make CMakeFiles/pracownik.dir/src/Tables.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kierownik.dir/build.make CMakeFiles/kierownik.dir/src/Tables.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SO.dir/build.make CMakeFiles/SO.dir/src/Tables.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/src/Tables.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/src/Tables.cpp.i
.PHONY : src/Tables.cpp.i

src/Tables.s: src/Tables.cpp.s
.PHONY : src/Tables.s

# target to generate assembly for a file
src/Tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/klient.dir/build.make CMakeFiles/klient.dir/src/Tables.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator_klientow.dir/build.make CMakeFiles/generator_klientow.dir/src/Tables.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pracownik.dir/build.make CMakeFiles/pracownik.dir/src/Tables.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kierownik.dir/build.make CMakeFiles/kierownik.dir/src/Tables.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SO.dir/build.make CMakeFiles/SO.dir/src/Tables.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/src/Tables.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/src/Tables.cpp.s
.PHONY : src/Tables.cpp.s

src/generator_klientow.o: src/generator_klientow.cpp.o
.PHONY : src/generator_klientow.o

# target to build an object file
src/generator_klientow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator_klientow.dir/build.make CMakeFiles/generator_klientow.dir/src/generator_klientow.cpp.o
.PHONY : src/generator_klientow.cpp.o

src/generator_klientow.i: src/generator_klientow.cpp.i
.PHONY : src/generator_klientow.i

# target to preprocess a source file
src/generator_klientow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator_klientow.dir/build.make CMakeFiles/generator_klientow.dir/src/generator_klientow.cpp.i
.PHONY : src/generator_klientow.cpp.i

src/generator_klientow.s: src/generator_klientow.cpp.s
.PHONY : src/generator_klientow.s

# target to generate assembly for a file
src/generator_klientow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator_klientow.dir/build.make CMakeFiles/generator_klientow.dir/src/generator_klientow.cpp.s
.PHONY : src/generator_klientow.cpp.s

src/kasjer.o: src/kasjer.cpp.o
.PHONY : src/kasjer.o

# target to build an object file
src/kasjer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/src/kasjer.cpp.o
.PHONY : src/kasjer.cpp.o

src/kasjer.i: src/kasjer.cpp.i
.PHONY : src/kasjer.i

# target to preprocess a source file
src/kasjer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/src/kasjer.cpp.i
.PHONY : src/kasjer.cpp.i

src/kasjer.s: src/kasjer.cpp.s
.PHONY : src/kasjer.s

# target to generate assembly for a file
src/kasjer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/src/kasjer.cpp.s
.PHONY : src/kasjer.cpp.s

src/kierownik.o: src/kierownik.cpp.o
.PHONY : src/kierownik.o

# target to build an object file
src/kierownik.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kierownik.dir/build.make CMakeFiles/kierownik.dir/src/kierownik.cpp.o
.PHONY : src/kierownik.cpp.o

src/kierownik.i: src/kierownik.cpp.i
.PHONY : src/kierownik.i

# target to preprocess a source file
src/kierownik.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kierownik.dir/build.make CMakeFiles/kierownik.dir/src/kierownik.cpp.i
.PHONY : src/kierownik.cpp.i

src/kierownik.s: src/kierownik.cpp.s
.PHONY : src/kierownik.s

# target to generate assembly for a file
src/kierownik.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kierownik.dir/build.make CMakeFiles/kierownik.dir/src/kierownik.cpp.s
.PHONY : src/kierownik.cpp.s

src/klient.o: src/klient.cpp.o
.PHONY : src/klient.o

# target to build an object file
src/klient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/klient.dir/build.make CMakeFiles/klient.dir/src/klient.cpp.o
.PHONY : src/klient.cpp.o

src/klient.i: src/klient.cpp.i
.PHONY : src/klient.i

# target to preprocess a source file
src/klient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/klient.dir/build.make CMakeFiles/klient.dir/src/klient.cpp.i
.PHONY : src/klient.cpp.i

src/klient.s: src/klient.cpp.s
.PHONY : src/klient.s

# target to generate assembly for a file
src/klient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/klient.dir/build.make CMakeFiles/klient.dir/src/klient.cpp.s
.PHONY : src/klient.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SO.dir/build.make CMakeFiles/SO.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SO.dir/build.make CMakeFiles/SO.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SO.dir/build.make CMakeFiles/SO.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pracownik.o: src/pracownik.cpp.o
.PHONY : src/pracownik.o

# target to build an object file
src/pracownik.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pracownik.dir/build.make CMakeFiles/pracownik.dir/src/pracownik.cpp.o
.PHONY : src/pracownik.cpp.o

src/pracownik.i: src/pracownik.cpp.i
.PHONY : src/pracownik.i

# target to preprocess a source file
src/pracownik.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pracownik.dir/build.make CMakeFiles/pracownik.dir/src/pracownik.cpp.i
.PHONY : src/pracownik.cpp.i

src/pracownik.s: src/pracownik.cpp.s
.PHONY : src/pracownik.s

# target to generate assembly for a file
src/pracownik.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pracownik.dir/build.make CMakeFiles/pracownik.dir/src/pracownik.cpp.s
.PHONY : src/pracownik.cpp.s

src/wrappers.o: src/wrappers.cpp.o
.PHONY : src/wrappers.o

# target to build an object file
src/wrappers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/klient.dir/build.make CMakeFiles/klient.dir/src/wrappers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator_klientow.dir/build.make CMakeFiles/generator_klientow.dir/src/wrappers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pracownik.dir/build.make CMakeFiles/pracownik.dir/src/wrappers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kierownik.dir/build.make CMakeFiles/kierownik.dir/src/wrappers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SO.dir/build.make CMakeFiles/SO.dir/src/wrappers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/src/wrappers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/src/wrappers.cpp.o
.PHONY : src/wrappers.cpp.o

src/wrappers.i: src/wrappers.cpp.i
.PHONY : src/wrappers.i

# target to preprocess a source file
src/wrappers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/klient.dir/build.make CMakeFiles/klient.dir/src/wrappers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator_klientow.dir/build.make CMakeFiles/generator_klientow.dir/src/wrappers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pracownik.dir/build.make CMakeFiles/pracownik.dir/src/wrappers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kierownik.dir/build.make CMakeFiles/kierownik.dir/src/wrappers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SO.dir/build.make CMakeFiles/SO.dir/src/wrappers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/src/wrappers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/src/wrappers.cpp.i
.PHONY : src/wrappers.cpp.i

src/wrappers.s: src/wrappers.cpp.s
.PHONY : src/wrappers.s

# target to generate assembly for a file
src/wrappers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/klient.dir/build.make CMakeFiles/klient.dir/src/wrappers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generator_klientow.dir/build.make CMakeFiles/generator_klientow.dir/src/wrappers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pracownik.dir/build.make CMakeFiles/pracownik.dir/src/wrappers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kierownik.dir/build.make CMakeFiles/kierownik.dir/src/wrappers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SO.dir/build.make CMakeFiles/SO.dir/src/wrappers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/src/wrappers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kasjer.dir/build.make CMakeFiles/kasjer.dir/src/wrappers.cpp.s
.PHONY : src/wrappers.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SO"
	@echo "... generator_klientow"
	@echo "... kasjer"
	@echo "... kierownik"
	@echo "... klient"
	@echo "... logger"
	@echo "... pracownik"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/Tables.o"
	@echo "... src/Tables.i"
	@echo "... src/Tables.s"
	@echo "... src/generator_klientow.o"
	@echo "... src/generator_klientow.i"
	@echo "... src/generator_klientow.s"
	@echo "... src/kasjer.o"
	@echo "... src/kasjer.i"
	@echo "... src/kasjer.s"
	@echo "... src/kierownik.o"
	@echo "... src/kierownik.i"
	@echo "... src/kierownik.s"
	@echo "... src/klient.o"
	@echo "... src/klient.i"
	@echo "... src/klient.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pracownik.o"
	@echo "... src/pracownik.i"
	@echo "... src/pracownik.s"
	@echo "... src/wrappers.o"
	@echo "... src/wrappers.i"
	@echo "... src/wrappers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

